name: load_more_flutter
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.8.2+3

  distinct_value_connectable_observable: ^2.0.3
  rxdart: ^0.22.3
  rx_redux: ^1.0.0

  collection: ^1.14.11
  tuple: ^1.0.2
  built_value: ^6.6.0
  cached_network_image: ^1.1.1

#flutter packages pub run build_runner build

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.5.2
  built_value_generator: ^6.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/people.json
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
