name: load_more_flutter
description: Load more data when scroll to end of ListView Flutter.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.0+1

  distinct_value_connectable_stream: ^1.0.3+1
  rxdart: ^0.23.1
  rx_redux: ^1.1.0
  disposebag: ^1.1.1+1

  collection: ^1.14.11
  tuple: ^1.0.2
  built_value: ^7.0.8
  built_collection: ^4.3.2
  cached_network_image: ^2.0.0
  http: ^0.12.0+4

#flutter packages pub run build_runner build

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  built_value_generator: ^7.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/json/people.json
flutter_intl:
  enabled: true
